# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  # COMMENTED OUT: Papers menu item (Featured Publications section is hidden)
  # - name: Papers
  #   url: /#papers
  #   weight: 11
  # COMMENTED OUT: Talks menu item (Recent & Upcoming Talks section is hidden)  
  # - name: Talks
  #   url: /#talks
  #   weight: 12
  # COMMENTED OUT: News menu item (Recent News section is hidden)
  # - name: News
  #   url: /#news
  #   weight: 13
  - name: Experience
    url: experience/
    weight: 20
  # COMMENTED OUT: Projects menu item - uncomment when ready to use
  # - name: Projects
  #   url: projects/
  #   weight: 30
  # COMMENTED OUT: Teaching menu item - uncomment when ready to use
  # - name: Teaching
  #   url: teaching/
  #   weight: 40
